#!/bin/vbash

# Allow ICMP
set firewall all-ping 'enable'

# Containers
set firewall name containers-guest default-action 'drop'
set firewall name containers-guest description 'From CONTAINERS to GUEST'
set firewall name containers-lab default-action 'accept'
set firewall name containers-lab description 'From CONTAINERS to LAB'
set firewall name containers-lan default-action 'accept'
set firewall name containers-lan description 'From CONTAINERS to LAN'
set firewall name containers-local default-action 'accept'
set firewall name containers-local description 'From CONTAINERS to LOCAL'
set firewall name containers-lab default-action 'accept'
set firewall name containers-wan default-action 'accept'
set firewall name containers-wan description 'From CONTAINERS to WAN'
set firewall name containers-wireguard default-action 'accept'
set firewall name containers-wireguard description 'From CONTAINERS to WIREGUARD'
set firewall name containers-wireless default-action 'accept'
set firewall name containers-wireless description 'From CONTAINERS to WIRELESS'

# Guest
set firewall name guest-containers default-action 'drop'
set firewall name guest-containers description 'From GUEST to CONTAINERS'
set firewall name guest-lab default-action 'drop'
set firewall name guest-lab description 'From GUEST to LAB'
set firewall name guest-lan default-action 'drop'
set firewall name guest-lan description 'From GUEST to LAN'
set firewall name guest-local default-action 'drop'
set firewall name guest-local description 'From GUEST to LOCAL'
set firewall name guest-wan default-action 'accept'
set firewall name guest-wan description 'From GUEST to WAN'
set firewall name guest-wireguard default-action 'drop'
set firewall name guest-wireguard description 'From GUEST to WIREGUARD'
set firewall name guest-wireless default-action 'drop'
set firewall name guest-wireless description 'From GUEST to WIRELESS'

# Lab
set firewall name lab-containers default-action 'accept'
set firewall name lab-containers description 'From LAB to CONTAINERS'
set firewall name lab-guest default-action 'accept'
set firewall name lab-guest description 'From LAB to GUEST'
set firewall name lab-lan default-action 'accept'
set firewall name lab-lan description 'From LAB to LAN'
set firewall name lab-local default-action 'accept'
set firewall name lab-local description 'From LAB to LOCAL'
set firewall name lab-wan default-action 'accept'
set firewall name lab-wan description 'From LAB to WAN'
set firewall name lab-wireguard default-action 'accept'
set firewall name lab-wireguard description 'From LAB to WIREGUARD'
set firewall name lab-wireless default-action 'accept'
set firewall name lab-wireless description 'From LAB to WIRELESS'

# LAN
set firewall name lan-containers default-action 'accept'
set firewall name lan-containers description 'From LAN to CONTAINERS'
set firewall name lan-guest default-action 'accept'
set firewall name lan-guest description 'From LAN to GUEST'
set firewall name lan-lab default-action 'accept'
set firewall name lan-lab description 'From LAN to LAB'
set firewall name lan-local default-action 'accept'
set firewall name lan-local description 'From LAN to LOCAL'
set firewall name lan-lab description 'From LAN to LAB'
set firewall name lan-wan default-action 'accept'
set firewall name lan-wan description 'From LAN to WAN'
set firewall name lan-wireguard default-action 'accept'
set firewall name lan-wireguard description 'From LAN to WIREGUARD'
set firewall name lan-wireless default-action 'accept'
set firewall name lan-wireless description 'From LAN to WIRELESS'

# LOCAL
set firewall name local-containers default-action 'accept'
set firewall name local-containers description 'From LOCAL to CONTAINERS'
set firewall name local-guest default-action 'accept'
set firewall name local-guest description 'From LOCAL to GUEST'
set firewall name local-lab default-action 'accept'
set firewall name local-lab description 'From LOCAL to LAB'
set firewall name local-lan default-action 'accept'
set firewall name local-lan description 'From LOCAL to LAN'
set firewall name local-wan default-action 'accept'
set firewall name local-wan description 'From LOCAL to WAN'
set firewall name local-wireguard default-action 'accept'
set firewall name local-wireguard description 'From LOCAL to WIREGUARD'
set firewall name local-wireless default-action 'accept'
set firewall name local-wireless description 'From LOCAL to WIRELESS'

# WAN
set firewall name wan-containers default-action 'drop'
set firewall name wan-containers description 'From WAN to CONTAINERS'
set firewall name wan-containers enable-default-log
set firewall name wan-guest default-action 'drop'
set firewall name wan-guest description 'From WAN to GUEST'
set firewall name wan-guest enable-default-log
set firewall name wan-lab default-action 'drop'`
set firewall name wan-lab description 'From WAN to LAB'
set firewall name wan-lab enable-default-log
set firewall name wan-lan default-action 'drop'
set firewall name wan-lan description 'From WAN to LAN'
set firewall name wan-lan enable-default-log
set firewall name wan-local default-action 'drop'
set firewall name wan-local description 'From WAN to LOCAL'
set firewall name wan-local enable-default-log
set firewall name wan-local rule 400 action 'accept'
set firewall name wan-local rule 400 description 'Rule: Accept Wireguard'
set firewall name wan-local rule 400 destination port '51820'
set firewall name wan-local rule 400 protocol 'udp'
set firewall name wan-lab rule 700 description 'Rule: Accept SE traffic'
set firewall name wan-lab rule 700 destination address '10.10.10.52'
set firewall name wan-lab rule 700 destination port '27016'
set firewall name wan-lab rule 700 protocol 'udp'
set firewall name wan-lab rule 700 action 'accept'
set firewall name wan-wireguard default-action 'drop'
set firewall name wan-wireguard description 'From WAN to WIREGUARD'
set firewall name wan-wireguard enable-default-log
set firewall name wan-wireless default-action 'drop'
set firewall name wan-wireless description 'From WAN to WIRELESS'
set firewall name wan-wireless enable-default-log

# WIREGUARD
set firewall name wireguard-containers default-action 'accept'
set firewall name wireguard-containers description 'From WIREGUARD to CONTAINERS'
set firewall name wireguard-guest default-action 'accept'
set firewall name wireguard-guest description 'From WIREGUARD to GUEST'
set firewall name wireguard-lab default-action 'accept'
set firewall name wireguard-lab description 'From WIREGUARD to LAB'
set firewall name wireguard-lan default-action 'accept'
set firewall name wireguard-lan description 'From WIREGUARD to LAN'
set firewall name wireguard-local default-action 'accept'
set firewall name wireguard-local description 'From WIREGUARD to LOCAL'
set firewall name wireguard-wan default-action 'accept'
set firewall name wireguard-wan description 'From WIREGUARD to WAN'
set firewall name wireguard-wireless default-action 'accept'
set firewall name wireguard-wireless description 'From WIREGUARD to WIRELESS'
set firewall name wireless-containers default-action 'accept'
set firewall name wireless-containers description 'From WIRELESS to CONTAINERS'
set firewall name wireless-guest default-action 'accept'
set firewall name wireless-guest description 'From WIRELESS to GUEST'
set firewall name wireless-lab default-action 'accept'
set firewall name wireless-lab description 'From WIRELESS to LAB'
set firewall name wireless-lan default-action 'accept'
set firewall name wireless-lan description 'From WIRELESS to LAN'
set firewall name wireless-local default-action 'accept'
set firewall name wireless-local description 'From WIRELESS to LOCAL'
set firewall name wireless-wan default-action 'accept'
set firewall name wireless-wan description 'From WIRELESS to WAN'
set firewall name wireless-wireguard default-action 'accept'
set firewall name wireless-wireguard description 'From WIRELESS to WIREGUARD'

# Policies
set firewall state-policy established action 'accept'
set firewall state-policy invalid action 'drop'
set firewall state-policy related action 'accept'